apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: book-app
spec:
  selector:
    app: analytics-service
  ports:
    - name: http
      port: 5010
      targetPort: 5010
  type: ClusterIP 