apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: book-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
      - name: analytics-service
        image: analytics-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5010
        env:
        - name: MONGO_URL
          value: mongodb://mongo:27017/analyticsdb
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 5010
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 5010
          initialDelaySeconds: 15
          periodSeconds: 20 