apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: book-app
  labels:
    app: auth-service
spec:
  ports:
  - port: 5001
    targetPort: 5001
    protocol: TCP
    name: http
  selector:
    app: auth-service
  type: ClusterIP 