apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: book-service
type: Opaque
data:
  # JWT_SECRET: base64 encoded "your-super-secret-jwt-key-change-in-production"
  JWT_SECRET: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1jaGFuZ2UtaW4tcHJvZHVjdGlvbg==
  # DB_PASSWORD: base64 encoded "password"
  DB_PASSWORD: cGFzc3dvcmQ= 