apiVersion: v1
kind: Service
metadata:
  name: auth-mysql
  namespace: book-app
  labels:
    app: auth-mysql
spec:
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
    name: mysql
  selector:
    app: auth-mysql
  type: ClusterIP 