apiVersion: v1
kind: Service
metadata:
  name: book-service
  namespace: book-app
spec:
  selector:
    app: book-service
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  type: ClusterIP 