apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: book-app
spec:
  selector:
    app: cart-service
  ports:
    - name: http
      port: 5005
      targetPort: 5000
  type: ClusterIP 