apiVersion: v1
kind: Service
metadata:
  name: kong
  namespace: book-app
spec:
  type: NodePort
  ports:
    - name: proxy
      port: 8000
      targetPort: 8000
      nodePort: 30080
    - name: admin
      port: 8001
      targetPort: 8001
      nodePort: 30081
  selector:
    app: kong 