apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: book-app
spec:
  selector:
    app: order-service
  ports:
    - name: http
      port: 5006
      targetPort: 5000
  type: ClusterIP 