apiVersion: v1
kind: Service
metadata:
  name: publisher-service
  namespace: book-app
spec:
  selector:
    app: publisher-service
  ports:
    - name: http
      port: 5002
      targetPort: 5000
  type: ClusterIP 