apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: publisher-mongo
  namespace: book-app
spec:
  serviceName: publisher-mongo
  replicas: 1
  selector:
    matchLabels:
      app: publisher-mongo
  template:
    metadata:
      labels:
        app: publisher-mongo
    spec:
      containers:
      - name: mongo
        image: mongo:6.0
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: publisher-mongo-secret
              key: mongo-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: publisher-mongo-secret
              key: mongo-password
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
      volumes:
      - name: mongo-persistent-storage
        persistentVolumeClaim:
          claimName: publisher-mongo-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: publisher-mongo-pvc
  namespace: book-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi 