apiVersion: v1
kind: Service
metadata:
  name: search-service
  namespace: book-app
spec:
  selector:
    app: search-service
  ports:
    - name: http
      port: 5004
      targetPort: 5000
  type: ClusterIP 