apiVersion: v1
kind: Service
metadata:
  name: service-registry
  namespace: book-app
spec:
  selector:
    app: service-registry
  ports:
    - name: http
      port: 5007
      targetPort: 5007
  type: ClusterIP 