apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-registry
  namespace: book-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-registry
  template:
    metadata:
      labels:
        app: service-registry
    spec:
      containers:
      - name: service-registry
        image: service-registry:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5007
        env:
        - name: MONGO_URL
          value: mongodb://mongo:mongo123@service-registry-mongo:27017/registrydb?authSource=admin
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 5007
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 5007
          initialDelaySeconds: 15
          periodSeconds: 20 