apiVersion: v1
kind: Service
metadata:
  name: service-registry-mongo
  namespace: book-app
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: service-registry-mongo
  type: ClusterIP 