apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: book-app
spec:
  selector:
    app: user-service
  ports:
    - name: http
      port: 5001
      targetPort: 5000
  type: ClusterIP 